name: Pre-Commit

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install vscode-task-runner
        run: pipx install vscode-task-runner

      - name: Cache Pre-Commit
        uses: NathanVaughn/actions-pre-commit-cache@main

      - name: Run Pre-Commit Hooks
        run: pre-commit run --all-files --color=always --show-diff-on-failure
